# Generated by Django 3.0.8 on 2020-07-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20200712_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='', help_text='Enter with a book author', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='headquarter',
            field=models.CharField(default='', help_text='Enter with your headquarter', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='', help_text='Select a book cover', max_length=300, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0, help_text='Enter with a total of pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(default='', help_text='Enter with a book title', max_length=200),
        ),
    ]
